[terminal]

# The VT to run the greeter on. Can be "next", "current" or a number
vt = 7

# The default session, also known as the greeter.
[default_session]

command = "tuigreet --cmd 'startx >/dev/null 2>&1' --time --remember-user-session"
# # `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# # with whatever you want started, such as `sway`.
# command = "/usr/sbin/agreety --cmd /bin/sh"
# # if using wlgreet
# #command = "sway --config /etc/greetd/sway-config"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "_greetd"
